apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-v7cj
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-vrsa-tenant/rhtap-demo-app/hacbs-test-project-v7cj@sha256:1a82509796d1add3759da2f8cba206162e567d61db007d7b07201df354b30c6d
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
