apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-v7cj
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-v7cj
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-v7cj
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-v7cj
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-v7cj
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-vrsa-tenant/rhtap-demo-app/hacbs-test-project-v7cj@sha256:1a82509796d1add3759da2f8cba206162e567d61db007d7b07201df354b30c6d
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
